name: Update Nodes API

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: |
        cd APIs/
        python get.py

    - name: Check for changes
      run: |
        git status
        if [[ $(git status --porcelain APIs/nodefree.txt APIs/nodeshare.txt APIs/clashgithub.txt) ]]; then
          git add APIs/nodefree.txt
          git add APIs/nodeshare.txt
          git add APIs/clashgithub.txt
          git status
          git commit -m "Update files"
          git push https://github.com/${{ github.repository }} HEAD:main
        else
          echo "No changes to commit"
        fi
      env:
        PAT: ${{ secrets.PAT }}
    
    
