name: Update Nodes API

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: |
        cd APIs/
        python get.py

    - name: Check for changes
      run: |
        git status
        if [[ $(git status --porcelain APIs/nodefree.txt APIs/nodeshare.txt APIs/cg0.txt APIs/cg1.txt APIs/cg2.txt APIs/cg3.txt APIs/cg4.txt APIs/sc0.yaml APIs/sc1.yaml APIs/sc2.yaml APIs/sc3.yaml APIs/sc4.yaml) ]]; then
          git add APIs/cg0.txt
          git add APIs/cg1.txt
          git add APIs/cg2.txt
          git add APIs/cg3.txt
          git add APIs/cg4.txt
          git add APIs/sc0.yaml
          git add APIs/sc1.yaml
          git add APIs/sc2.yaml
          git add APIs/sc3.yaml
          git add APIs/sc4.yaml
          git status
          git commit -m "Update files"
          git push https://github.com/${{ github.repository }} HEAD:main
        else
          echo "No changes to commit"
        fi
      env:
        PAT: ${{ secrets.PAT }}
